nginx:
  build: docker/nginx
  ports:
    - "80:80"
  links:
    - php
  volumes:
    - ./:/project:cached

php:
  build: docker/php
  volumes:
    - ./:/project:cached
    - ~/.ssh:/home/vagrant/.ssh
  working_dir: /project
  links:
    - db

db:
  image: mysql:latest
  volumes:
     - /var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_DATABASE=appdb_dev
    - MYSQL_ROOT_PASSWORD=changeme
