nginx:
  build: docker/nginx
  ports:
    - "80:80"
  links:
    - php
  volumes:
    - ./:/project:cached

php:
  build: docker/php
  volumes:
    - ./:/project:cached
    - ~/.ssh:/home/vagrant/.ssh
  working_dir: /project/citytree.nl
  links:
    - db
    - mailhog
db:
  image: mysql:latest
  volumes:
     - /var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_DATABASE=citytree_dev
    - MYSQL_ROOT_PASSWORD=1xpjwwdk

mailhog:
  image: mailhog/mailhog:latest
  ports:
    - "8025:8025"
    - "1025:1025"

